DROP DATABASE IF EXISTS REGISTRADURIA;
CREATE DATABASE IF NOT EXISTS REGISTRADURIA;

USE REGISTRADURIA;

CREATE TABLE IF NOT EXISTS VOTACIONES(
	ID INT auto_increment PRIMARY KEY,
    TIPO VARCHAR(25) NOT NULL,
    FECHA DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS UBICACIONES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTAMENTO VARCHAR(35) NOT NULL,
    CIUDAD VARCHAR(35) NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSONAS(
	ID BINARY(16) PRIMARY KEY DEFAULT(UUID_TO_BIN(UUID())),
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO VARCHAR(25) NOT NULL,
    CEDULA VARCHAR(255) NOT NULL UNIQUE,
    UBICACION INT NOT NULL,
	CONTRASEÑA VARCHAR(255) NOT NULL,
    CONSTRAINT FOREIGN KEY (UBICACION) REFERENCES UBICACIONES(ID)
);

CREATE TABLE IF NOT EXISTS PERSONAS_VOTACIONES(
    PERSONA BINARY(16) NOT NULL,
    VOTACION INT NOT NULL,
    DISPONIBLE BOOLEAN NOT NULL DEFAULT 1,
    
    CONSTRAINT FOREIGN KEY (PERSONA) REFERENCES PERSONAS(ID),
    CONSTRAINT FOREIGN KEY (VOTACION) REFERENCES VOTACIONES(ID),
    CONSTRAINT PRIMARY KEY (PERSONA, VOTACION)
);

CREATE TABLE IF NOT EXISTS CANDIDATOS_VOTACIONES (
	ID BINARY(16) PRIMARY KEY DEFAULT(UUID_TO_BIN(UUID())),
    PERSONA BINARY(16) NOT NULL UNIQUE, /* Este se vuelve candidato, lo que quiere decir que debe ser unico*/
    VOTACION INT NOT NULL,
    VOTOS BIGINT NOT NULL DEFAULT(0),
    
    CONSTRAINT FOREIGN KEY (PERSONA) REFERENCES PERSONAS(ID),
    CONSTRAINT FOREIGN KEY (VOTACION) REFERENCES VOTACIONES(ID)
);