SELECT BIN_TO_UUID(P.ID) ID, P.NOMBRE, APELLIDO, CEDULA, CONTRASEÑA, dp.nombre DEPARTAMENTO ,ci.nombre CIUDAD 
FROM PERSONAS P 
JOIN CIUDADES ci 
ON ci.ID = P.CIUDAD
JOIN DEPARTAMENTOS DP
ON ci.DEPARTAMENTO = DP.ID;
SELECT * FROM VOTACIONES;
INSERT INTO PERSONAS_VOTACIONES (PERSONA, VOTACION) VALUES
((SELECT ID FROM PERSONAS WHERE CEDULA='12345'), 1),
((SELECT ID FROM PERSONAS WHERE CEDULA='12345'), 2),
((SELECT ID FROM PERSONAS WHERE CEDULA='12345'), 3),
((SELECT ID FROM PERSONAS WHERE CEDULA='53214'), 1),
((SELECT ID FROM PERSONAS WHERE CEDULA='53214'), 2),
((SELECT ID FROM PERSONAS WHERE CEDULA='53214'), 3),
((SELECT ID FROM PERSONAS WHERE CEDULA='4915495'), 1),
((SELECT ID FROM PERSONAS WHERE CEDULA='4915495'), 2),
((SELECT ID FROM PERSONAS WHERE CEDULA='4915495'), 3),
((SELECT ID FROM PERSONAS WHERE CEDULA='64859451'), 1),
((SELECT ID FROM PERSONAS WHERE CEDULA='64859451'), 2),
((SELECT ID FROM PERSONAS WHERE CEDULA='64859451'), 3);


select * from PERSONAS_VOTACIONES PV JOIN PERSONAS P ON P.ID = PV.PERSONA;