select DISTINCT cedula from PERSONAS_VOTACIONES PV JOIN PERSONAS P ON P.ID = PV.PERSONA;
SELECT * FROM PERSONAS WHERE CEDULA <> '12345' AND CEDULA <> '53214' AND CEDULA <> '4915495' AND CEDULA <> '64859451';
SELECT * FROM VOTACIONES;
INSERT INTO CANDIDATOS_VOTACIONES (PERSONA, VOTACION) VALUES
((SELECT ID FROM PERSONAS WHERE CEDULA='54321'), 1),
((SELECT ID FROM PERSONAS WHERE CEDULA='5674891'), 2),
((SELECT ID FROM PERSONAS WHERE CEDULA='8989898'), 3),
((SELECT ID FROM PERSONAS WHERE CEDULA='123456'), 1);


select * from CANDIDATOS_VOTACIONES PV JOIN PERSONAS P ON P.ID = PV.PERSONA;